/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package examples;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class FollowJointTrajectoryFeedback implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public int current_point;

    public double error;

    public double progress;

 
    public FollowJointTrajectoryFeedback()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf52683da03d1513eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(examples.FollowJointTrajectoryFeedback.class))
            return 0L;
 
        classes.add(examples.FollowJointTrajectoryFeedback.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.current_point); 
 
        outs.writeDouble(this.error); 
 
        outs.writeDouble(this.progress); 
 
    }
 
    public FollowJointTrajectoryFeedback(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public FollowJointTrajectoryFeedback(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static examples.FollowJointTrajectoryFeedback _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        examples.FollowJointTrajectoryFeedback o = new examples.FollowJointTrajectoryFeedback();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.current_point = ins.readInt();
 
        this.error = ins.readDouble();
 
        this.progress = ins.readDouble();
 
    }
 
    public examples.FollowJointTrajectoryFeedback copy()
    {
        examples.FollowJointTrajectoryFeedback outobj = new examples.FollowJointTrajectoryFeedback();
        outobj.header = this.header.copy();
 
        outobj.current_point = this.current_point;
 
        outobj.error = this.error;
 
        outobj.progress = this.progress;
 
        return outobj;
    }
 
}

