/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package examples;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Service types for simple math operations
 */
public final class AddNumbersRequest implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public double a;

    public double b;

 
    public AddNumbersRequest()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x04b4b622d2331f28L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(examples.AddNumbersRequest.class))
            return 0L;
 
        classes.add(examples.AddNumbersRequest.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeDouble(this.a); 
 
        outs.writeDouble(this.b); 
 
    }
 
    public AddNumbersRequest(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public AddNumbersRequest(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static examples.AddNumbersRequest _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        examples.AddNumbersRequest o = new examples.AddNumbersRequest();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.a = ins.readDouble();
 
        this.b = ins.readDouble();
 
    }
 
    public examples.AddNumbersRequest copy()
    {
        examples.AddNumbersRequest outobj = new examples.AddNumbersRequest();
        outobj.header = this.header.copy();
 
        outobj.a = this.a;
 
        outobj.b = this.b;
 
        return outobj;
    }
 
}

