/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package examples;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class AddNumbersResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

    public double sum;

 
    public AddNumbersResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa0c2e19c6be048afL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(examples.AddNumbersResponse.class))
            return 0L;
 
        classes.add(examples.AddNumbersResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.response_header._encodeRecursive(outs); 
 
        outs.writeDouble(this.sum); 
 
    }
 
    public AddNumbersResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public AddNumbersResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static examples.AddNumbersResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        examples.AddNumbersResponse o = new examples.AddNumbersResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
        this.sum = ins.readDouble();
 
    }
 
    public examples.AddNumbersResponse copy()
    {
        examples.AddNumbersResponse outobj = new examples.AddNumbersResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.sum = this.sum;
 
        return outobj;
    }
 
}

