/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package examples;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class FollowJointTrajectoryResult implements lcm.lcm.LCMEncodable
{
    public core.ActionStatus status;

    public double final_error;

    public double execution_time;

 
    public FollowJointTrajectoryResult()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8ee9eef590c2e137L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(examples.FollowJointTrajectoryResult.class))
            return 0L;
 
        classes.add(examples.FollowJointTrajectoryResult.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ActionStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.status._encodeRecursive(outs); 
 
        outs.writeDouble(this.final_error); 
 
        outs.writeDouble(this.execution_time); 
 
    }
 
    public FollowJointTrajectoryResult(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public FollowJointTrajectoryResult(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static examples.FollowJointTrajectoryResult _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        examples.FollowJointTrajectoryResult o = new examples.FollowJointTrajectoryResult();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = core.ActionStatus._decodeRecursiveFactory(ins);
 
        this.final_error = ins.readDouble();
 
        this.execution_time = ins.readDouble();
 
    }
 
    public examples.FollowJointTrajectoryResult copy()
    {
        examples.FollowJointTrajectoryResult outobj = new examples.FollowJointTrajectoryResult();
        outobj.status = this.status.copy();
 
        outobj.final_error = this.final_error;
 
        outobj.execution_time = this.execution_time;
 
        return outobj;
    }
 
}

