/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package grip;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class GripResult implements lcm.lcm.LCMEncodable
{
    public core.ActionStatus status;

    public int state;

    public float position;

 
    public GripResult()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3b4318f88964ec57L;
 
    public static final int MOVING = 1;
    public static final int FINISHED = 3;
    public static final int OBJECT_FOUND = 4;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(grip.GripResult.class))
            return 0L;
 
        classes.add(grip.GripResult.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ActionStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.status._encodeRecursive(outs); 
 
        outs.writeInt(this.state); 
 
        outs.writeFloat(this.position); 
 
    }
 
    public GripResult(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public GripResult(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static grip.GripResult _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        grip.GripResult o = new grip.GripResult();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = core.ActionStatus._decodeRecursiveFactory(ins);
 
        this.state = ins.readInt();
 
        this.position = ins.readFloat();
 
    }
 
    public grip.GripResult copy()
    {
        grip.GripResult outobj = new grip.GripResult();
        outobj.status = this.status.copy();
 
        outobj.state = this.state;
 
        outobj.position = this.position;
 
        return outobj;
    }
 
}

