"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ActionStatus(object):
    """
    Action status values:
    1 = ActionStatus::ACCEPTED
    2 = ActionStatus::EXECUTING  
    3 = ActionStatus::SUCCEEDED
    4 = ActionStatus::ABORTED
    5 = ActionStatus::CANCELED
    """

    __slots__ = ["header", "status", "message"]

    __typenames__ = ["core.Header", "int8_t", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.status = 0
        """ LCM Type: int8_t """
        self.message = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(ActionStatus._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">b", self.status))
        __message_encoded = self.message.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_encoded)+1))
        buf.write(__message_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ActionStatus._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ActionStatus._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ActionStatus()
        self.header = core.Header._decode_one(buf)
        self.status = struct.unpack(">b", buf.read(1))[0]
        __message_len = struct.unpack('>I', buf.read(4))[0]
        self.message = buf.read(__message_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ActionStatus in parents: return 0
        newparents = parents + [ActionStatus]
        tmphash = (0x8357197188faba20+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ActionStatus._packed_fingerprint is None:
            ActionStatus._packed_fingerprint = struct.pack(">Q", ActionStatus._get_hash_recursive([]))
        return ActionStatus._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ActionStatus._get_packed_fingerprint())[0]

