"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ActionCancel(object):
    """ Action control messages """

    __slots__ = ["header", "goal_id"]

    __typenames__ = ["core.Header", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.goal_id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(ActionCancel._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __goal_id_encoded = self.goal_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__goal_id_encoded)+1))
        buf.write(__goal_id_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ActionCancel._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ActionCancel._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ActionCancel()
        self.header = core.Header._decode_one(buf)
        __goal_id_len = struct.unpack('>I', buf.read(4))[0]
        self.goal_id = buf.read(__goal_id_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ActionCancel in parents: return 0
        newparents = parents + [ActionCancel]
        tmphash = (0x221c17446d0e4377+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ActionCancel._packed_fingerprint is None:
            ActionCancel._packed_fingerprint = struct.pack(">Q", ActionCancel._get_hash_recursive([]))
        return ActionCancel._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ActionCancel._get_packed_fingerprint())[0]

