"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class BoolMsg(object):
    """ Primitive data types """

    __slots__ = ["header", "value"]

    __typenames__ = ["core.Header", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.value = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(BoolMsg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">b", self.value))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != BoolMsg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return BoolMsg._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = BoolMsg()
        self.header = core.Header._decode_one(buf)
        self.value = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if BoolMsg in parents: return 0
        newparents = parents + [BoolMsg]
        tmphash = (0x41b5023b3bac2291+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if BoolMsg._packed_fingerprint is None:
            BoolMsg._packed_fingerprint = struct.pack(">Q", BoolMsg._get_hash_recursive([]))
        return BoolMsg._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", BoolMsg._get_packed_fingerprint())[0]

