"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class BoolServiceResponse(object):

    __slots__ = ["response_header", "result"]

    __typenames__ = ["core.ServiceResponseHeader", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.response_header = core.ServiceResponseHeader()
        """ LCM Type: core.ServiceResponseHeader """
        self.result = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(BoolServiceResponse._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.response_header._get_packed_fingerprint() == core.ServiceResponseHeader._get_packed_fingerprint()
        self.response_header._encode_one(buf)
        buf.write(struct.pack(">b", self.result))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != BoolServiceResponse._get_packed_fingerprint():
            raise ValueError("Decode error")
        return BoolServiceResponse._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = BoolServiceResponse()
        self.response_header = core.ServiceResponseHeader._decode_one(buf)
        self.result = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if BoolServiceResponse in parents: return 0
        newparents = parents + [BoolServiceResponse]
        tmphash = (0x65df8daf840960eb+ core.ServiceResponseHeader._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if BoolServiceResponse._packed_fingerprint is None:
            BoolServiceResponse._packed_fingerprint = struct.pack(">Q", BoolServiceResponse._get_hash_recursive([]))
        return BoolServiceResponse._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", BoolServiceResponse._get_packed_fingerprint())[0]

