"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class BoolArrayMsg(object):

    __slots__ = ["header", "data_size", "data"]

    __typenames__ = ["core.Header", "int32_t", "boolean"]

    __dimensions__ = [None, None, ["data_size"]]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.data_size = 0
        """ LCM Type: int32_t """
        self.data = []
        """ LCM Type: boolean[data_size] """

    def encode(self):
        buf = BytesIO()
        buf.write(BoolArrayMsg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">i", self.data_size))
        buf.write(struct.pack('>%db' % self.data_size, *self.data[:self.data_size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != BoolArrayMsg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return BoolArrayMsg._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = BoolArrayMsg()
        self.header = core.Header._decode_one(buf)
        self.data_size = struct.unpack(">i", buf.read(4))[0]
        self.data = [bool(x) for x in struct.unpack('>%db' % self.data_size, buf.read(self.data_size))]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if BoolArrayMsg in parents: return 0
        newparents = parents + [BoolArrayMsg]
        tmphash = (0x7eeaff93cb34815+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if BoolArrayMsg._packed_fingerprint is None:
            BoolArrayMsg._packed_fingerprint = struct.pack(">Q", BoolArrayMsg._get_hash_recursive([]))
        return BoolArrayMsg._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", BoolArrayMsg._get_packed_fingerprint())[0]

