"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class DoubleServiceRequest(object):

    __slots__ = ["header", "value"]

    __typenames__ = ["core.Header", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.value = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(DoubleServiceRequest._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">d", self.value))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DoubleServiceRequest._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DoubleServiceRequest._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = DoubleServiceRequest()
        self.header = core.Header._decode_one(buf)
        self.value = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if DoubleServiceRequest in parents: return 0
        newparents = parents + [DoubleServiceRequest]
        tmphash = (0xc7bc4b03bacb576f+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if DoubleServiceRequest._packed_fingerprint is None:
            DoubleServiceRequest._packed_fingerprint = struct.pack(">Q", DoubleServiceRequest._get_hash_recursive([]))
        return DoubleServiceRequest._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", DoubleServiceRequest._get_packed_fingerprint())[0]

