"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class EmptyResponse(object):

    __slots__ = ["response_header"]

    __typenames__ = ["core.ResponseHeader"]

    __dimensions__ = [None]

    def __init__(self):
        self.response_header = core.ResponseHeader()
        """ LCM Type: core.ResponseHeader """

    def encode(self):
        buf = BytesIO()
        buf.write(EmptyResponse._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.response_header._get_packed_fingerprint() == core.ResponseHeader._get_packed_fingerprint()
        self.response_header._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != EmptyResponse._get_packed_fingerprint():
            raise ValueError("Decode error")
        return EmptyResponse._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = EmptyResponse()
        self.response_header = core.ResponseHeader._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if EmptyResponse in parents: return 0
        newparents = parents + [EmptyResponse]
        tmphash = (0xbbccb38ab2d0c608+ core.ResponseHeader._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if EmptyResponse._packed_fingerprint is None:
            EmptyResponse._packed_fingerprint = struct.pack(">Q", EmptyResponse._get_hash_recursive([]))
        return EmptyResponse._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", EmptyResponse._get_packed_fingerprint())[0]

