"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class FileRequest(object):
    """ File operations """

    __slots__ = ["header", "operation", "path", "data_size", "data"]

    __typenames__ = ["core.Header", "string", "string", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None, ["data_size"]]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.operation = ""
        """ LCM Type: string """
        self.path = ""
        """
        "read", "write", "delete", "list"
        LCM Type: string
        """

        self.data_size = 0
        """ LCM Type: int32_t """
        self.data = []
        """ LCM Type: int8_t[data_size] """

    def encode(self):
        buf = BytesIO()
        buf.write(FileRequest._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __operation_encoded = self.operation.encode('utf-8')
        buf.write(struct.pack('>I', len(__operation_encoded)+1))
        buf.write(__operation_encoded)
        buf.write(b"\0")
        __path_encoded = self.path.encode('utf-8')
        buf.write(struct.pack('>I', len(__path_encoded)+1))
        buf.write(__path_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.data_size))
        buf.write(struct.pack('>%db' % self.data_size, *self.data[:self.data_size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FileRequest._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FileRequest._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = FileRequest()
        self.header = core.Header._decode_one(buf)
        __operation_len = struct.unpack('>I', buf.read(4))[0]
        self.operation = buf.read(__operation_len)[:-1].decode('utf-8', 'replace')
        __path_len = struct.unpack('>I', buf.read(4))[0]
        self.path = buf.read(__path_len)[:-1].decode('utf-8', 'replace')
        self.data_size = struct.unpack(">i", buf.read(4))[0]
        self.data = struct.unpack('>%db' % self.data_size, buf.read(self.data_size))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if FileRequest in parents: return 0
        newparents = parents + [FileRequest]
        tmphash = (0x34020d1af7aaeb08+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if FileRequest._packed_fingerprint is None:
            FileRequest._packed_fingerprint = struct.pack(">Q", FileRequest._get_hash_recursive([]))
        return FileRequest._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FileRequest._get_packed_fingerprint())[0]

