"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class FileResponse(object):

    __slots__ = ["response_header", "data_size", "data", "file_size", "modified_time"]

    __typenames__ = ["core.ServiceResponseHeader", "int32_t", "int8_t", "int64_t", "int64_t"]

    __dimensions__ = [None, None, ["data_size"], None, None]

    def __init__(self):
        self.response_header = core.ServiceResponseHeader()
        """ LCM Type: core.ServiceResponseHeader """
        self.data_size = 0
        """ LCM Type: int32_t """
        self.data = []
        """ LCM Type: int8_t[data_size] """
        self.file_size = 0
        """
        file contents or directory listing
        LCM Type: int64_t
        """

        self.modified_time = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(FileResponse._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.response_header._get_packed_fingerprint() == core.ServiceResponseHeader._get_packed_fingerprint()
        self.response_header._encode_one(buf)
        buf.write(struct.pack(">i", self.data_size))
        buf.write(struct.pack('>%db' % self.data_size, *self.data[:self.data_size]))
        buf.write(struct.pack(">qq", self.file_size, self.modified_time))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FileResponse._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FileResponse._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = FileResponse()
        self.response_header = core.ServiceResponseHeader._decode_one(buf)
        self.data_size = struct.unpack(">i", buf.read(4))[0]
        self.data = struct.unpack('>%db' % self.data_size, buf.read(self.data_size))
        self.file_size, self.modified_time = struct.unpack(">qq", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if FileResponse in parents: return 0
        newparents = parents + [FileResponse]
        tmphash = (0xac80d7c5b8cb8182+ core.ServiceResponseHeader._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if FileResponse._packed_fingerprint is None:
            FileResponse._packed_fingerprint = struct.pack(">Q", FileResponse._get_hash_recursive([]))
        return FileResponse._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FileResponse._get_packed_fingerprint())[0]

