"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class Heartbeat(object):
    """ Heartbeat/ping """

    __slots__ = ["header", "node_name", "sequence_number"]

    __typenames__ = ["core.Header", "string", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.node_name = ""
        """ LCM Type: string """
        self.sequence_number = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(Heartbeat._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __node_name_encoded = self.node_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__node_name_encoded)+1))
        buf.write(__node_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.sequence_number))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Heartbeat._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Heartbeat._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Heartbeat()
        self.header = core.Header._decode_one(buf)
        __node_name_len = struct.unpack('>I', buf.read(4))[0]
        self.node_name = buf.read(__node_name_len)[:-1].decode('utf-8', 'replace')
        self.sequence_number = struct.unpack(">q", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Heartbeat in parents: return 0
        newparents = parents + [Heartbeat]
        tmphash = (0x890cfe9f1649524f+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Heartbeat._packed_fingerprint is None:
            Heartbeat._packed_fingerprint = struct.pack(">Q", Heartbeat._get_hash_recursive([]))
        return Heartbeat._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Heartbeat._get_packed_fingerprint())[0]

