"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class KeyValueMsg(object):
    """
    ========================================
    System Utility Types
    ========================================
    Key-Value pair
    """

    __slots__ = ["header", "key", "value"]

    __typenames__ = ["core.Header", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.key = ""
        """ LCM Type: string """
        self.value = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(KeyValueMsg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __key_encoded = self.key.encode('utf-8')
        buf.write(struct.pack('>I', len(__key_encoded)+1))
        buf.write(__key_encoded)
        buf.write(b"\0")
        __value_encoded = self.value.encode('utf-8')
        buf.write(struct.pack('>I', len(__value_encoded)+1))
        buf.write(__value_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != KeyValueMsg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return KeyValueMsg._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = KeyValueMsg()
        self.header = core.Header._decode_one(buf)
        __key_len = struct.unpack('>I', buf.read(4))[0]
        self.key = buf.read(__key_len)[:-1].decode('utf-8', 'replace')
        __value_len = struct.unpack('>I', buf.read(4))[0]
        self.value = buf.read(__value_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if KeyValueMsg in parents: return 0
        newparents = parents + [KeyValueMsg]
        tmphash = (0x777f354b01022c64+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if KeyValueMsg._packed_fingerprint is None:
            KeyValueMsg._packed_fingerprint = struct.pack(">Q", KeyValueMsg._get_hash_recursive([]))
        return KeyValueMsg._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", KeyValueMsg._get_packed_fingerprint())[0]

