"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ProcessDataFeedback(object):

    __slots__ = ["header", "progress", "items_processed", "total_items"]

    __typenames__ = ["core.Header", "double", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.progress = 0.0
        """ LCM Type: double """
        self.items_processed = 0
        """ LCM Type: int32_t """
        self.total_items = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(ProcessDataFeedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">dii", self.progress, self.items_processed, self.total_items))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ProcessDataFeedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ProcessDataFeedback._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ProcessDataFeedback()
        self.header = core.Header._decode_one(buf)
        self.progress, self.items_processed, self.total_items = struct.unpack(">dii", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ProcessDataFeedback in parents: return 0
        newparents = parents + [ProcessDataFeedback]
        tmphash = (0x2fac7c69432cd348+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ProcessDataFeedback._packed_fingerprint is None:
            ProcessDataFeedback._packed_fingerprint = struct.pack(">Q", ProcessDataFeedback._get_hash_recursive([]))
        return ProcessDataFeedback._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ProcessDataFeedback._get_packed_fingerprint())[0]

