"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ProcessDataResult(object):

    __slots__ = ["status", "result_size", "result", "processing_time"]

    __typenames__ = ["core.ActionStatus", "int32_t", "int8_t", "double"]

    __dimensions__ = [None, None, ["result_size"], None]

    def __init__(self):
        self.status = core.ActionStatus()
        """ LCM Type: core.ActionStatus """
        self.result_size = 0
        """ LCM Type: int32_t """
        self.result = []
        """ LCM Type: int8_t[result_size] """
        self.processing_time = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(ProcessDataResult._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.status._get_packed_fingerprint() == core.ActionStatus._get_packed_fingerprint()
        self.status._encode_one(buf)
        buf.write(struct.pack(">i", self.result_size))
        buf.write(struct.pack('>%db' % self.result_size, *self.result[:self.result_size]))
        buf.write(struct.pack(">d", self.processing_time))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ProcessDataResult._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ProcessDataResult._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ProcessDataResult()
        self.status = core.ActionStatus._decode_one(buf)
        self.result_size = struct.unpack(">i", buf.read(4))[0]
        self.result = struct.unpack('>%db' % self.result_size, buf.read(self.result_size))
        self.processing_time = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ProcessDataResult in parents: return 0
        newparents = parents + [ProcessDataResult]
        tmphash = (0x1a21329683acf36a+ core.ActionStatus._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ProcessDataResult._packed_fingerprint is None:
            ProcessDataResult._packed_fingerprint = struct.pack(">Q", ProcessDataResult._get_hash_recursive([]))
        return ProcessDataResult._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ProcessDataResult._get_packed_fingerprint())[0]

