"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ResponseHeader(object):
    """ Service response wrapper (all services use this) """

    __slots__ = ["header", "success", "error_message"]

    __typenames__ = ["core.Header", "boolean", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.success = False
        """ LCM Type: boolean """
        self.error_message = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(ResponseHeader._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">b", self.success))
        __error_message_encoded = self.error_message.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_message_encoded)+1))
        buf.write(__error_message_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ResponseHeader._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ResponseHeader._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ResponseHeader()
        self.header = core.Header._decode_one(buf)
        self.success = bool(struct.unpack('b', buf.read(1))[0])
        __error_message_len = struct.unpack('>I', buf.read(4))[0]
        self.error_message = buf.read(__error_message_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ResponseHeader in parents: return 0
        newparents = parents + [ResponseHeader]
        tmphash = (0x2044cb6f96d5fd3e+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ResponseHeader._packed_fingerprint is None:
            ResponseHeader._packed_fingerprint = struct.pack(">Q", ResponseHeader._get_hash_recursive([]))
        return ResponseHeader._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ResponseHeader._get_packed_fingerprint())[0]

