"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class StringArrayMsg(object):

    __slots__ = ["header", "data_size", "data"]

    __typenames__ = ["core.Header", "int32_t", "string"]

    __dimensions__ = [None, None, ["data_size"]]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.data_size = 0
        """ LCM Type: int32_t """
        self.data = []
        """ LCM Type: string[data_size] """

    def encode(self):
        buf = BytesIO()
        buf.write(StringArrayMsg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">i", self.data_size))
        for i0 in range(self.data_size):
            __data_encoded = self.data[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__data_encoded)+1))
            buf.write(__data_encoded)
            buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != StringArrayMsg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return StringArrayMsg._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = StringArrayMsg()
        self.header = core.Header._decode_one(buf)
        self.data_size = struct.unpack(">i", buf.read(4))[0]
        self.data = []
        for i0 in range(self.data_size):
            __data_len = struct.unpack('>I', buf.read(4))[0]
            self.data.append(buf.read(__data_len)[:-1].decode('utf-8', 'replace'))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if StringArrayMsg in parents: return 0
        newparents = parents + [StringArrayMsg]
        tmphash = (0xb0eb365c0a6629fc+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if StringArrayMsg._packed_fingerprint is None:
            StringArrayMsg._packed_fingerprint = struct.pack(">Q", StringArrayMsg._get_hash_recursive([]))
        return StringArrayMsg._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", StringArrayMsg._get_packed_fingerprint())[0]

