"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class StringMsg(object):

    __slots__ = ["header", "value"]

    __typenames__ = ["core.Header", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.value = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(StringMsg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        __value_encoded = self.value.encode('utf-8')
        buf.write(struct.pack('>I', len(__value_encoded)+1))
        buf.write(__value_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != StringMsg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return StringMsg._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = StringMsg()
        self.header = core.Header._decode_one(buf)
        __value_len = struct.unpack('>I', buf.read(4))[0]
        self.value = buf.read(__value_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if StringMsg in parents: return 0
        newparents = parents + [StringMsg]
        tmphash = (0xc7ad5000c1cd596f+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if StringMsg._packed_fingerprint is None:
            StringMsg._packed_fingerprint = struct.pack(">Q", StringMsg._get_hash_recursive([]))
        return StringMsg._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", StringMsg._get_packed_fingerprint())[0]

