"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class StringResponse(object):

    __slots__ = ["response_header", "result"]

    __typenames__ = ["core.ResponseHeader", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.response_header = core.ResponseHeader()
        """ LCM Type: core.ResponseHeader """
        self.result = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(StringResponse._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.response_header._get_packed_fingerprint() == core.ResponseHeader._get_packed_fingerprint()
        self.response_header._encode_one(buf)
        __result_encoded = self.result.encode('utf-8')
        buf.write(struct.pack('>I', len(__result_encoded)+1))
        buf.write(__result_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != StringResponse._get_packed_fingerprint():
            raise ValueError("Decode error")
        return StringResponse._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = StringResponse()
        self.response_header = core.ResponseHeader._decode_one(buf)
        __result_len = struct.unpack('>I', buf.read(4))[0]
        self.result = buf.read(__result_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if StringResponse in parents: return 0
        newparents = parents + [StringResponse]
        tmphash = (0xf48925755372fc31+ core.ResponseHeader._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if StringResponse._packed_fingerprint is None:
            StringResponse._packed_fingerprint = struct.pack(">Q", StringResponse._get_hash_recursive([]))
        return StringResponse._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", StringResponse._get_packed_fingerprint())[0]

