"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class TimedActionResult(object):

    __slots__ = ["status", "actual_duration"]

    __typenames__ = ["core.ActionStatus", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.status = core.ActionStatus()
        """ LCM Type: core.ActionStatus """
        self.actual_duration = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(TimedActionResult._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.status._get_packed_fingerprint() == core.ActionStatus._get_packed_fingerprint()
        self.status._encode_one(buf)
        buf.write(struct.pack(">d", self.actual_duration))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimedActionResult._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimedActionResult._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = TimedActionResult()
        self.status = core.ActionStatus._decode_one(buf)
        self.actual_duration = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if TimedActionResult in parents: return 0
        newparents = parents + [TimedActionResult]
        tmphash = (0xad7083eb13af0ee0+ core.ActionStatus._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if TimedActionResult._packed_fingerprint is None:
            TimedActionResult._packed_fingerprint = struct.pack(">Q", TimedActionResult._get_hash_recursive([]))
        return TimedActionResult._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimedActionResult._get_packed_fingerprint())[0]

