"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class TimedActionFeedback(object):

    __slots__ = ["header", "progress", "elapsed_seconds", "remaining_seconds"]

    __typenames__ = ["core.Header", "double", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.progress = 0.0
        """ LCM Type: double """
        self.elapsed_seconds = 0.0
        """
        0.0 to 1.0
        LCM Type: double
        """

        self.remaining_seconds = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(TimedActionFeedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">ddd", self.progress, self.elapsed_seconds, self.remaining_seconds))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimedActionFeedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimedActionFeedback._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = TimedActionFeedback()
        self.header = core.Header._decode_one(buf)
        self.progress, self.elapsed_seconds, self.remaining_seconds = struct.unpack(">ddd", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if TimedActionFeedback in parents: return 0
        newparents = parents + [TimedActionFeedback]
        tmphash = (0xbd2d867775ff472a+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if TimedActionFeedback._packed_fingerprint is None:
            TimedActionFeedback._packed_fingerprint = struct.pack(">Q", TimedActionFeedback._get_hash_recursive([]))
        return TimedActionFeedback._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimedActionFeedback._get_packed_fingerprint())[0]

