"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class TimedActionGoal(object):
    """ Generic timed action (wait/delay) """

    __slots__ = ["header", "duration_seconds"]

    __typenames__ = ["core.Header", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.duration_seconds = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(TimedActionGoal._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">d", self.duration_seconds))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimedActionGoal._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimedActionGoal._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = TimedActionGoal()
        self.header = core.Header._decode_one(buf)
        self.duration_seconds = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if TimedActionGoal in parents: return 0
        newparents = parents + [TimedActionGoal]
        tmphash = (0x66833192280df016+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if TimedActionGoal._packed_fingerprint is None:
            TimedActionGoal._packed_fingerprint = struct.pack(">Q", TimedActionGoal._get_hash_recursive([]))
        return TimedActionGoal._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimedActionGoal._get_packed_fingerprint())[0]

