"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class UInt32Request(object):

    __slots__ = ["header", "value"]

    __typenames__ = ["core.Header", "int32_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.value = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(UInt32Request._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">i", self.value))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != UInt32Request._get_packed_fingerprint():
            raise ValueError("Decode error")
        return UInt32Request._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = UInt32Request()
        self.header = core.Header._decode_one(buf)
        self.value = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if UInt32Request in parents: return 0
        newparents = parents + [UInt32Request]
        tmphash = (0x48b5fd746eae1c91+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if UInt32Request._packed_fingerprint is None:
            UInt32Request._packed_fingerprint = struct.pack(">Q", UInt32Request._get_hash_recursive([]))
        return UInt32Request._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", UInt32Request._get_packed_fingerprint())[0]

