"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class GripFeedback(object):

    __slots__ = ["header", "a"]

    __typenames__ = ["core.Header", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.a = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(GripFeedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">b", self.a))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GripFeedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GripFeedback._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = GripFeedback()
        self.header = core.Header._decode_one(buf)
        self.a = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if GripFeedback in parents: return 0
        newparents = parents + [GripFeedback]
        tmphash = (0xd12c8028f9c15763+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if GripFeedback._packed_fingerprint is None:
            GripFeedback._packed_fingerprint = struct.pack(">Q", GripFeedback._get_hash_recursive([]))
        return GripFeedback._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", GripFeedback._get_packed_fingerprint())[0]

