"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class FollowJointTrajectoryFeedback(object):

    __slots__ = ["header", "current_point", "error", "progress"]

    __typenames__ = ["core.Header", "int32_t", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.current_point = 0
        """ LCM Type: int32_t """
        self.error = 0.0
        """ LCM Type: double """
        self.progress = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(FollowJointTrajectoryFeedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">idd", self.current_point, self.error, self.progress))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FollowJointTrajectoryFeedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FollowJointTrajectoryFeedback._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = FollowJointTrajectoryFeedback()
        self.header = core.Header._decode_one(buf)
        self.current_point, self.error, self.progress = struct.unpack(">idd", buf.read(20))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if FollowJointTrajectoryFeedback in parents: return 0
        newparents = parents + [FollowJointTrajectoryFeedback]
        tmphash = (0xf52683da03d1513e+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if FollowJointTrajectoryFeedback._packed_fingerprint is None:
            FollowJointTrajectoryFeedback._packed_fingerprint = struct.pack(">Q", FollowJointTrajectoryFeedback._get_hash_recursive([]))
        return FollowJointTrajectoryFeedback._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FollowJointTrajectoryFeedback._get_packed_fingerprint())[0]

