"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import core

class ImageMessage(object):
    """ Simple sensor message for topic demos """

    __slots__ = ["header", "width", "height", "channels", "encoding", "data_size", "data"]

    __typenames__ = ["core.Header", "int32_t", "int32_t", "int32_t", "string", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, ["data_size"]]

    def __init__(self):
        self.header = core.Header()
        """ LCM Type: core.Header """
        self.width = 0
        """ LCM Type: int32_t """
        self.height = 0
        """ LCM Type: int32_t """
        self.channels = 0
        """ LCM Type: int32_t """
        self.encoding = ""
        """ LCM Type: string """
        self.data_size = 0
        """ LCM Type: int32_t """
        self.data = []
        """ LCM Type: int8_t[data_size] """

    def encode(self):
        buf = BytesIO()
        buf.write(ImageMessage._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == core.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">iii", self.width, self.height, self.channels))
        __encoding_encoded = self.encoding.encode('utf-8')
        buf.write(struct.pack('>I', len(__encoding_encoded)+1))
        buf.write(__encoding_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.data_size))
        buf.write(struct.pack('>%db' % self.data_size, *self.data[:self.data_size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ImageMessage._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ImageMessage._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ImageMessage()
        self.header = core.Header._decode_one(buf)
        self.width, self.height, self.channels = struct.unpack(">iii", buf.read(12))
        __encoding_len = struct.unpack('>I', buf.read(4))[0]
        self.encoding = buf.read(__encoding_len)[:-1].decode('utf-8', 'replace')
        self.data_size = struct.unpack(">i", buf.read(4))[0]
        self.data = struct.unpack('>%db' % self.data_size, buf.read(self.data_size))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ImageMessage in parents: return 0
        newparents = parents + [ImageMessage]
        tmphash = (0x5f79e8dbcd0c9cc1+ core.Header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ImageMessage._packed_fingerprint is None:
            ImageMessage._packed_fingerprint = struct.pack(">Q", ImageMessage._get_hash_recursive([]))
        return ImageMessage._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ImageMessage._get_packed_fingerprint())[0]

