/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Action control messages
 */
public final class ActionCancel implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public String goal_id;

 
    public ActionCancel()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x221c17446d0e4377L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.ActionCancel.class))
            return 0L;
 
        classes.add(core.ActionCancel.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        __strbuf = new char[this.goal_id.length()]; this.goal_id.getChars(0, this.goal_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public ActionCancel(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ActionCancel(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.ActionCancel _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.ActionCancel o = new core.ActionCancel();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.goal_id = new String(__strbuf);
 
    }
 
    public core.ActionCancel copy()
    {
        core.ActionCancel outobj = new core.ActionCancel();
        outobj.header = this.header.copy();
 
        outobj.goal_id = this.goal_id;
 
        return outobj;
    }
 
}

