/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Generic command/response
 */
public final class CommandMsg implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public String command;

    public int args_size;

    /**
     * LCM Type: string[args_size]
     */
    public String args[];

 
    public CommandMsg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe02c6175665c5731L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.CommandMsg.class))
            return 0L;
 
        classes.add(core.CommandMsg.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        __strbuf = new char[this.command.length()]; this.command.getChars(0, this.command.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.args_size); 
 
        for (int a = 0; a < this.args_size; a++) {
            __strbuf = new char[this.args[a].length()]; this.args[a].getChars(0, this.args[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
    }
 
    public CommandMsg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public CommandMsg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.CommandMsg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.CommandMsg o = new core.CommandMsg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.command = new String(__strbuf);
 
        this.args_size = ins.readInt();
 
        this.args = new String[(int) args_size];
        for (int a = 0; a < this.args_size; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.args[a] = new String(__strbuf);
        }
 
    }
 
    public core.CommandMsg copy()
    {
        core.CommandMsg outobj = new core.CommandMsg();
        outobj.header = this.header.copy();
 
        outobj.command = this.command;
 
        outobj.args_size = this.args_size;
 
        outobj.args = new String[(int) args_size];
        if (this.args_size > 0)
            System.arraycopy(this.args, 0, outobj.args, 0, (int) this.args_size); 
        return outobj;
    }
 
}

