/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class HeartbeatResponse implements lcm.lcm.LCMEncodable
{
    public core.ResponseHeader response_header;

    public long server_timestamp_us;

    public String server_name;

 
    public HeartbeatResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9e7b39a2c45d0a1aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.HeartbeatResponse.class))
            return 0L;
 
        classes.add(core.HeartbeatResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.response_header._encodeRecursive(outs); 
 
        outs.writeLong(this.server_timestamp_us); 
 
        __strbuf = new char[this.server_name.length()]; this.server_name.getChars(0, this.server_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public HeartbeatResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public HeartbeatResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.HeartbeatResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.HeartbeatResponse o = new core.HeartbeatResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.response_header = core.ResponseHeader._decodeRecursiveFactory(ins);
 
        this.server_timestamp_us = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.server_name = new String(__strbuf);
 
    }
 
    public core.HeartbeatResponse copy()
    {
        core.HeartbeatResponse outobj = new core.HeartbeatResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.server_timestamp_us = this.server_timestamp_us;
 
        outobj.server_name = this.server_name;
 
        return outobj;
    }
 
}

