/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ProcessDataResult implements lcm.lcm.LCMEncodable
{
    public core.ActionStatus status;

    public int result_size;

    /**
     * LCM Type: int8_t[result_size]
     */
    public byte result[];

    public double processing_time;

 
    public ProcessDataResult()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1a21329683acf36aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.ProcessDataResult.class))
            return 0L;
 
        classes.add(core.ProcessDataResult.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ActionStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.status._encodeRecursive(outs); 
 
        outs.writeInt(this.result_size); 
 
        if (this.result_size > 0)
            outs.write(this.result, 0, (int) result_size);
 
        outs.writeDouble(this.processing_time); 
 
    }
 
    public ProcessDataResult(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ProcessDataResult(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.ProcessDataResult _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.ProcessDataResult o = new core.ProcessDataResult();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = core.ActionStatus._decodeRecursiveFactory(ins);
 
        this.result_size = ins.readInt();
 
        this.result = new byte[(int) result_size];
        ins.readFully(this.result, 0, (int) result_size); 
        this.processing_time = ins.readDouble();
 
    }
 
    public core.ProcessDataResult copy()
    {
        core.ProcessDataResult outobj = new core.ProcessDataResult();
        outobj.status = this.status.copy();
 
        outobj.result_size = this.result_size;
 
        outobj.result = new byte[(int) result_size];
        if (this.result_size > 0)
            System.arraycopy(this.result, 0, outobj.result, 0, (int) this.result_size); 
        outobj.processing_time = this.processing_time;
 
        return outobj;
    }
 
}

