/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Generic timed action (wait/delay)
 */
public final class TimedActionGoal implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public double duration_seconds;

 
    public TimedActionGoal()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x66833192280df016L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.TimedActionGoal.class))
            return 0L;
 
        classes.add(core.TimedActionGoal.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeDouble(this.duration_seconds); 
 
    }
 
    public TimedActionGoal(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TimedActionGoal(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.TimedActionGoal _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.TimedActionGoal o = new core.TimedActionGoal();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.duration_seconds = ins.readDouble();
 
    }
 
    public core.TimedActionGoal copy()
    {
        core.TimedActionGoal outobj = new core.TimedActionGoal();
        outobj.header = this.header.copy();
 
        outobj.duration_seconds = this.duration_seconds;
 
        return outobj;
    }
 
}

