/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class TimedActionFeedback implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public double progress;

    /**
     * 0.0 to 1.0
     */
    public double elapsed_seconds;

    public double remaining_seconds;

 
    public TimedActionFeedback()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xbd2d867775ff472aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.TimedActionFeedback.class))
            return 0L;
 
        classes.add(core.TimedActionFeedback.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeDouble(this.progress); 
 
        outs.writeDouble(this.elapsed_seconds); 
 
        outs.writeDouble(this.remaining_seconds); 
 
    }
 
    public TimedActionFeedback(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TimedActionFeedback(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.TimedActionFeedback _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.TimedActionFeedback o = new core.TimedActionFeedback();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.progress = ins.readDouble();
 
        this.elapsed_seconds = ins.readDouble();
 
        this.remaining_seconds = ins.readDouble();
 
    }
 
    public core.TimedActionFeedback copy()
    {
        core.TimedActionFeedback outobj = new core.TimedActionFeedback();
        outobj.header = this.header.copy();
 
        outobj.progress = this.progress;
 
        outobj.elapsed_seconds = this.elapsed_seconds;
 
        outobj.remaining_seconds = this.remaining_seconds;
 
        return outobj;
    }
 
}

