/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Action status values:
 * 1 = ActionStatus::ACCEPTED
 * 2 = ActionStatus::EXECUTING  
 * 3 = ActionStatus::SUCCEEDED
 * 4 = ActionStatus::ABORTED
 * 5 = ActionStatus::CANCELED
 */
public final class ActionStatus implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public byte status;

    public String message;

 
    public ActionStatus()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8357197188faba20L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.ActionStatus.class))
            return 0L;
 
        classes.add(core.ActionStatus.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        outs.writeByte(this.status); 
 
        __strbuf = new char[this.message.length()]; this.message.getChars(0, this.message.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public ActionStatus(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ActionStatus(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.ActionStatus _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.ActionStatus o = new core.ActionStatus();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.status = ins.readByte();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.message = new String(__strbuf);
 
    }
 
    public core.ActionStatus copy()
    {
        core.ActionStatus outobj = new core.ActionStatus();
        outobj.header = this.header.copy();
 
        outobj.status = this.status;
 
        outobj.message = this.message;
 
        return outobj;
    }
 
}

