/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Primitive data types
 */
public final class BoolMsg implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public boolean value;

 
    public BoolMsg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x41b5023b3bac2291L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.BoolMsg.class))
            return 0L;
 
        classes.add(core.BoolMsg.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeByte( this.value ? 1 : 0); 
 
    }
 
    public BoolMsg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public BoolMsg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.BoolMsg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.BoolMsg o = new core.BoolMsg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.value = ins.readByte()!=0;
 
    }
 
    public core.BoolMsg copy()
    {
        core.BoolMsg outobj = new core.BoolMsg();
        outobj.header = this.header.copy();
 
        outobj.value = this.value;
 
        return outobj;
    }
 
}

