/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class CommandResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

    public int exit_code;

    public String stdout_output;

    public String stderr_output;

 
    public CommandResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4a22f509f80490e9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.CommandResponse.class))
            return 0L;
 
        classes.add(core.CommandResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.response_header._encodeRecursive(outs); 
 
        outs.writeInt(this.exit_code); 
 
        __strbuf = new char[this.stdout_output.length()]; this.stdout_output.getChars(0, this.stdout_output.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.stderr_output.length()]; this.stderr_output.getChars(0, this.stderr_output.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public CommandResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public CommandResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.CommandResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.CommandResponse o = new core.CommandResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
        this.exit_code = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.stdout_output = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.stderr_output = new String(__strbuf);
 
    }
 
    public core.CommandResponse copy()
    {
        core.CommandResponse outobj = new core.CommandResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.exit_code = this.exit_code;
 
        outobj.stdout_output = this.stdout_output;
 
        outobj.stderr_output = this.stderr_output;
 
        return outobj;
    }
 
}

