/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * ========================================
 * Action Types
 * ========================================
 * Empty action (for testing/ping)
 */
public final class EmptyActionGoal implements lcm.lcm.LCMEncodable
{
    public core.Header header;

 
    public EmptyActionGoal()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0668656188ce1ef0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.EmptyActionGoal.class))
            return 0L;
 
        classes.add(core.EmptyActionGoal.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
    }
 
    public EmptyActionGoal(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public EmptyActionGoal(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.EmptyActionGoal _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.EmptyActionGoal o = new core.EmptyActionGoal();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
    }
 
    public core.EmptyActionGoal copy()
    {
        core.EmptyActionGoal outobj = new core.EmptyActionGoal();
        outobj.header = this.header.copy();
 
        return outobj;
    }
 
}

