/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class EmptyActionFeedback implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public double progress;

 
    public EmptyActionFeedback()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x88ded47d0bb9406eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.EmptyActionFeedback.class))
            return 0L;
 
        classes.add(core.EmptyActionFeedback.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeDouble(this.progress); 
 
    }
 
    public EmptyActionFeedback(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public EmptyActionFeedback(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.EmptyActionFeedback _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.EmptyActionFeedback o = new core.EmptyActionFeedback();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.progress = ins.readDouble();
 
    }
 
    public core.EmptyActionFeedback copy()
    {
        core.EmptyActionFeedback outobj = new core.EmptyActionFeedback();
        outobj.header = this.header.copy();
 
        outobj.progress = this.progress;
 
        return outobj;
    }
 
}

