/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class EmptyServiceResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

 
    public EmptyServiceResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xbbccb38ab2d0c608L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.EmptyServiceResponse.class))
            return 0L;
 
        classes.add(core.EmptyServiceResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.response_header._encodeRecursive(outs); 
 
    }
 
    public EmptyServiceResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public EmptyServiceResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.EmptyServiceResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.EmptyServiceResponse o = new core.EmptyServiceResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
    }
 
    public core.EmptyServiceResponse copy()
    {
        core.EmptyServiceResponse outobj = new core.EmptyServiceResponse();
        outobj.response_header = this.response_header.copy();
 
        return outobj;
    }
 
}

