/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class EmptyActionResult implements lcm.lcm.LCMEncodable
{
    public core.ActionStatus status;

 
    public EmptyActionResult()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0673746198de1ff0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.EmptyActionResult.class))
            return 0L;
 
        classes.add(core.EmptyActionResult.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ActionStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.status._encodeRecursive(outs); 
 
    }
 
    public EmptyActionResult(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public EmptyActionResult(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.EmptyActionResult _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.EmptyActionResult o = new core.EmptyActionResult();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = core.ActionStatus._decodeRecursiveFactory(ins);
 
    }
 
    public core.EmptyActionResult copy()
    {
        core.EmptyActionResult outobj = new core.EmptyActionResult();
        outobj.status = this.status.copy();
 
        return outobj;
    }
 
}

