/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class FileResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

    public int data_size;

    /**
     * LCM Type: int8_t[data_size]
     */
    public byte data[];

    /**
     * file contents or directory listing
     */
    public long file_size;

    public long modified_time;

 
    public FileResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xac80d7c5b8cb8182L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.FileResponse.class))
            return 0L;
 
        classes.add(core.FileResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.response_header._encodeRecursive(outs); 
 
        outs.writeInt(this.data_size); 
 
        if (this.data_size > 0)
            outs.write(this.data, 0, (int) data_size);
 
        outs.writeLong(this.file_size); 
 
        outs.writeLong(this.modified_time); 
 
    }
 
    public FileResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public FileResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.FileResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.FileResponse o = new core.FileResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
        this.data_size = ins.readInt();
 
        this.data = new byte[(int) data_size];
        ins.readFully(this.data, 0, (int) data_size); 
        this.file_size = ins.readLong();
 
        this.modified_time = ins.readLong();
 
    }
 
    public core.FileResponse copy()
    {
        core.FileResponse outobj = new core.FileResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.data_size = this.data_size;
 
        outobj.data = new byte[(int) data_size];
        if (this.data_size > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_size); 
        outobj.file_size = this.file_size;
 
        outobj.modified_time = this.modified_time;
 
        return outobj;
    }
 
}

