/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Heartbeat/ping
 */
public final class Heartbeat implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public String node_name;

    public long sequence_number;

 
    public Heartbeat()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x890cfe9f1649524fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.Heartbeat.class))
            return 0L;
 
        classes.add(core.Heartbeat.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        __strbuf = new char[this.node_name.length()]; this.node_name.getChars(0, this.node_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeLong(this.sequence_number); 
 
    }
 
    public Heartbeat(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Heartbeat(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.Heartbeat _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.Heartbeat o = new core.Heartbeat();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.node_name = new String(__strbuf);
 
        this.sequence_number = ins.readLong();
 
    }
 
    public core.Heartbeat copy()
    {
        core.Heartbeat outobj = new core.Heartbeat();
        outobj.header = this.header.copy();
 
        outobj.node_name = this.node_name;
 
        outobj.sequence_number = this.sequence_number;
 
        return outobj;
    }
 
}

