/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class IntArray implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public int data_size;

    /**
     * LCM Type: int32_t[data_size]
     */
    public int data[];

 
    public IntArray()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9654b4053ccf4400L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.IntArray.class))
            return 0L;
 
        classes.add(core.IntArray.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.data_size); 
 
        for (int a = 0; a < this.data_size; a++) {
            outs.writeInt(this.data[a]); 
        }
 
    }
 
    public IntArray(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public IntArray(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.IntArray _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.IntArray o = new core.IntArray();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.data_size = ins.readInt();
 
        this.data = new int[(int) data_size];
        for (int a = 0; a < this.data_size; a++) {
            this.data[a] = ins.readInt();
        }
 
    }
 
    public core.IntArray copy()
    {
        core.IntArray outobj = new core.IntArray();
        outobj.header = this.header.copy();
 
        outobj.data_size = this.data_size;
 
        outobj.data = new int[(int) data_size];
        if (this.data_size > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_size); 
        return outobj;
    }
 
}

