/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Data processing action
 */
public final class ProcessDataGoal implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public String operation;

    /**
     * "sort", "filter", "transform", etc.
     */
    public int data_size;

    /**
     * LCM Type: int8_t[data_size]
     */
    public byte data[];

 
    public ProcessDataGoal()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x69656acfa7cb3a9dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.ProcessDataGoal.class))
            return 0L;
 
        classes.add(core.ProcessDataGoal.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        __strbuf = new char[this.operation.length()]; this.operation.getChars(0, this.operation.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.data_size); 
 
        if (this.data_size > 0)
            outs.write(this.data, 0, (int) data_size);
 
    }
 
    public ProcessDataGoal(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ProcessDataGoal(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.ProcessDataGoal _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.ProcessDataGoal o = new core.ProcessDataGoal();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.operation = new String(__strbuf);
 
        this.data_size = ins.readInt();
 
        this.data = new byte[(int) data_size];
        ins.readFully(this.data, 0, (int) data_size); 
    }
 
    public core.ProcessDataGoal copy()
    {
        core.ProcessDataGoal outobj = new core.ProcessDataGoal();
        outobj.header = this.header.copy();
 
        outobj.operation = this.operation;
 
        outobj.data_size = this.data_size;
 
        outobj.data = new byte[(int) data_size];
        if (this.data_size > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_size); 
        return outobj;
    }
 
}

