/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Service response wrapper (all services use this)
 */
public final class ServiceResponseHeader implements lcm.lcm.LCMEncodable
{
    public core.Header header;

    public boolean success;

    public String error_message;

 
    public ServiceResponseHeader()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2044cb6f96d5fd3eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.ServiceResponseHeader.class))
            return 0L;
 
        classes.add(core.ServiceResponseHeader.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.header._encodeRecursive(outs); 
 
        outs.writeByte( this.success ? 1 : 0); 
 
        __strbuf = new char[this.error_message.length()]; this.error_message.getChars(0, this.error_message.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public ServiceResponseHeader(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ServiceResponseHeader(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.ServiceResponseHeader _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.ServiceResponseHeader o = new core.ServiceResponseHeader();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.header = core.Header._decodeRecursiveFactory(ins);
 
        this.success = ins.readByte()!=0;
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.error_message = new String(__strbuf);
 
    }
 
    public core.ServiceResponseHeader copy()
    {
        core.ServiceResponseHeader outobj = new core.ServiceResponseHeader();
        outobj.header = this.header.copy();
 
        outobj.success = this.success;
 
        outobj.error_message = this.error_message;
 
        return outobj;
    }
 
}

