/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class StringServiceResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

    public String result;

 
    public StringServiceResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf48925755372fc31L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.StringServiceResponse.class))
            return 0L;
 
        classes.add(core.StringServiceResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.response_header._encodeRecursive(outs); 
 
        __strbuf = new char[this.result.length()]; this.result.getChars(0, this.result.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public StringServiceResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public StringServiceResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.StringServiceResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.StringServiceResponse o = new core.StringServiceResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.result = new String(__strbuf);
 
    }
 
    public core.StringServiceResponse copy()
    {
        core.StringServiceResponse outobj = new core.StringServiceResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.result = this.result;
 
        return outobj;
    }
 
}

