/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class TimedActionResult implements lcm.lcm.LCMEncodable
{
    public core.ActionStatus status;

    public double actual_duration;

 
    public TimedActionResult()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xad7083eb13af0ee0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.TimedActionResult.class))
            return 0L;
 
        classes.add(core.TimedActionResult.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ActionStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.status._encodeRecursive(outs); 
 
        outs.writeDouble(this.actual_duration); 
 
    }
 
    public TimedActionResult(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TimedActionResult(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.TimedActionResult _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.TimedActionResult o = new core.TimedActionResult();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = core.ActionStatus._decodeRecursiveFactory(ins);
 
        this.actual_duration = ins.readDouble();
 
    }
 
    public core.TimedActionResult copy()
    {
        core.TimedActionResult outobj = new core.TimedActionResult();
        outobj.status = this.status.copy();
 
        outobj.actual_duration = this.actual_duration;
 
        return outobj;
    }
 
}

