/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class UInt32ServiceResponse implements lcm.lcm.LCMEncodable
{
    public core.ServiceResponseHeader response_header;

    public int result;

 
    public UInt32ServiceResponse()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6ce08876510b5aebL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(core.UInt32ServiceResponse.class))
            return 0L;
 
        classes.add(core.UInt32ServiceResponse.class);
        long hash = LCM_FINGERPRINT_BASE
             + core.ServiceResponseHeader._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.response_header._encodeRecursive(outs); 
 
        outs.writeInt(this.result); 
 
    }
 
    public UInt32ServiceResponse(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public UInt32ServiceResponse(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static core.UInt32ServiceResponse _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        core.UInt32ServiceResponse o = new core.UInt32ServiceResponse();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.response_header = core.ServiceResponseHeader._decodeRecursiveFactory(ins);
 
        this.result = ins.readInt();
 
    }
 
    public core.UInt32ServiceResponse copy()
    {
        core.UInt32ServiceResponse outobj = new core.UInt32ServiceResponse();
        outobj.response_header = this.response_header.copy();
 
        outobj.result = this.result;
 
        return outobj;
    }
 
}

